name: Make
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        git ls-files -z '*.css' '*.html' '*.js' '*.md' | xargs -0 touch
        git ls-files '*.css' '*.html' '*.js' '*.md'
        make > make.log
        cat make.log