name: Make
runs:
  using: composite
  steps:
    - run: |
        git ls-files -z '*.css' '*.html' '*.js' '*.md' | xargs -0 touch
        git ls-files -z '*.css' '*.html' '*.js' '*.md'
        make
      shell: bash
