name: Make
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - name: Pre
        run: |
          sudo apt-get update > /dev/null
          sudo apt-get install -y build-essential > /dev/null 2>&1
          npm ci > /dev/null
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "GitHub Actions Bot"
      - name: Make & commit
        run: |
          rm -rf *.css *.html *.js *.md
        # make
      - name: Post
        run: |
          git add .
          git commit -m "Commit Make changes" || :
          git push origin main