name: Make
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - uses: ./.github/actions/pre
      - uses: ./.github/actions/main
      - uses: ./.github/actions/post