name: Make
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - name: Make & commit
        run: ./action.sh
