name: Make
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
      - name: Setup Node
        uses: actions/setup-@v4
        with:
          node-version: lts/*
          cache: npm
      - name: Make & commit
        run: |
          npm ci
          make
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "GitHub Actions Bot"
          git add .
          git commit -m "Commit Make changes" || :
          git push origin main